/**
 * Writes the PostgreSQL variant of the schema from the SQLite one.
 *
 * Local development runs on a SQLite file so that `npm run setup` needs nothing
 * installed; the deployment runs on Neon Postgres. Prisma will not take the
 * provider from an environment variable, so rather than keep two schemas in step
 * by hand - which is how they drift - the Postgres one is generated from the
 * SQLite one at build time. The models are identical because the schema avoids
 * enums and Json columns, which are the only things that differ between them.
 *
 * Every substitution below is asserted. A silent miss here produces a schema
 * that still says sqlite, and the build fails much later with an error that
 * points nowhere near this file - which is exactly what happened once.
 */

import { readFile, writeFile } from "fs/promises";
import path from "path";

const source = path.join(process.cwd(), "prisma", "schema.prisma");
const target = path.join(process.cwd(), "prisma", "schema.postgres.prisma");

// Git may have checked the schema out with CRLF endings, so normalise before
// matching anything in it.
const schema = (await readFile(source, "utf8")).replace(/\r\n/g, "\n");

function substitute(text, pattern, replacement, what) {
  if (!pattern.test(text)) {
    throw new Error(
      `scripts/postgres-schema.mjs could not find ${what} in prisma/schema.prisma. ` +
        `The schema has changed shape - update this script rather than the generated file.`,
    );
  }
  return text.replace(pattern, replacement);
}

let postgres = substitute(
  schema,
  /datasource db \{[^}]*\}/,
  [
    "datasource db {",
    '  provider  = "postgresql"',
    '  url       = env("DATABASE_URL")',
    // Serverless functions go through Neon's pooler; DDL needs the direct
    // endpoint, which is what directUrl is for.
    '  directUrl = env("DIRECT_URL")',
    "}",
  ].join("\n"),
  "the datasource block",
);

postgres = substitute(
  postgres,
  /^\/\/ Nortex Industries/m,
  "// Generated by scripts/postgres-schema.mjs - edit prisma/schema.prisma instead.\n// Nortex Industries",
  "the header comment",
);

if (/provider\s*=\s*"sqlite"/.test(postgres)) {
  throw new Error("The generated Postgres schema still names the sqlite provider.");
}

await writeFile(target, postgres);
console.log(`Wrote ${path.relative(process.cwd(), target)} for PostgreSQL.`);
