/**
 * Writes the PostgreSQL variant of the schema from the SQLite one.
 *
 * Local development runs on a SQLite file so that `npm run setup` needs nothing
 * installed; the deployment runs on Neon Postgres. Prisma will not take the
 * provider from an environment variable, so rather than keep two schemas in step
 * by hand - which is how they drift - the Postgres one is generated from the
 * SQLite one at build time. The models are identical because the schema avoids
 * enums and Json columns, which are the only things that differ between them.
 */

import { readFile, writeFile } from "fs/promises";
import path from "path";

const source = path.join(process.cwd(), "prisma", "schema.prisma");
const target = path.join(process.cwd(), "prisma", "schema.postgres.prisma");

const schema = await readFile(source, "utf8");

if (!/provider\s*=\s*"sqlite"/.test(schema)) {
  throw new Error("prisma/schema.prisma no longer says sqlite - check before generating the Postgres variant.");
}

const postgres = schema
  .replace('provider = "sqlite"', 'provider = "postgresql"')
  .replace(
    "// Nortex Industries - Travel Expense Reimbursement",
    "// Generated by scripts/postgres-schema.mjs - edit prisma/schema.prisma instead.\n// Nortex Industries - Travel Expense Reimbursement",
  );

await writeFile(target, postgres);
console.log(`Wrote ${path.relative(process.cwd(), target)} for PostgreSQL.`);
